def build_graph(latents, k=70):
    ...
    return G

def compute_shortest_paths(G, pairs_idx):
    ...
    return shortest_paths

class CubicSpline:
    ...
    def optimize(self, decoder):
        ...